theme: jekyll-theme-slate
  
title: Brian NguyenAA
logo: "/images/me.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  [HOME](index.md)
